name: Build Image
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch: {}
  push:
    paths:
      - "Containerfile"
      - "setup.sh"

jobs:
  buid_base_image:
    name: 👻 Build Ghossty Base Image
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Debloat Runner
        run: |
          set +x ; set +e
          bash <(curl -qfsSL "https://raw.githubusercontent.com/pkgforge/devscripts/refs/heads/main/Github/Runners/debloat_ubuntu.sh")
        continue-on-error: true

      - name: Checkout ghostty-appimage
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Env
        run: |
          set +x ; set +e
          DOCKER_TAG="v$(date +'%Y.%m.%d')" && export DOCKER_TAG="$DOCKER_TAG"
          echo "DOCKER_TAG=$DOCKER_TAG" >> "${GITHUB_ENV}"
          echo "GHCR_NAME=ghcr.io/psadi/ghostty-appimage" >> "${GITHUB_ENV}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        continue-on-error: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        continue-on-error: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
        continue-on-error: true

      - name: Log in to Ghcr registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Containerfile
          push: ${{ github.ref_name == 'main' }}
          platforms: "linux/amd64,linux/arm64"
          tags: |
            ${{ env.GHCR_NAME }}:latest
            ${{ env.GHCR_NAME }}:${{ env.DOCKER_TAG }}

  # clean:
  #   needs:
  #     - buid_base_image
  #   runs-on: ubuntu-latest
  #   name: Delete old test images
  #   steps:
  #     - uses: snok/container-retention-policy@v3.0.0
  #       with:
  #         account: psadi
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         image-names: "ghostty-appimage"
  #         cut-off: 2w
  #         keep-n-most-recent: 2
  #         dry-run: true
